import {describe,expect,it} from 'vitest'
import {CENTRAL_INTERVIEW_CONTRACT,compileInterviewContext,compileInterviewPrompt,versionsCurrent} from './interviewContext'
import type {ContextPacket} from './types'
function packet():ContextPacket{return{schema:1,sessionId:'s',permission:'practice',question:{id:'q1',original:'Solve it',text:'Solve it',at:1},task:{objective:'Two sum',requirements:['Return indices'],constraints:[],phase:'implement',implementation:'allowed',version:3},evidenceVersion:7,codeVersion:4,contextKey:'ctx',conversation:[{sourceId:'a',at:1,role:'interviewer',text:'Can you optimize this?'}],files:[{path:'Main.java',language:'java',fileVersion:4,complete:false,fragments:[]}],knownPaths:['Main.java'],relations:[],visibleView:{origin:'screen',files:[{path:'Main.java',startLine:20,endLine:40}],terminalVisible:false},tests:[],patches:[],patchReviews:[],budget:{maxCharacters:10000,usedCharacters:0,omittedPaths:['Helper.java']}}}
describe('canonical interview context',()=>{
 it('shares problem, conversation, evidence and explicit unknowns across lanes',()=>{const c=compileInterviewContext(packet(),'guide');expect(c.problem.requirements).toContain('Return indices');expect(c.conversation?.[0].text).toContain('optimize');expect(c.evidence.unknown.join(' ')).toContain('Helper.java');expect(c.versions).toMatchObject({question:'q1',evidence:7,code:4,requirements:3})})
 it('keeps a stable central contract while lane instructions differ',()=>{const talk=compileInterviewPrompt(packet(),'talk'),guide=compileInterviewPrompt(packet(),'guide');expect(talk.system).toContain(CENTRAL_INTERVIEW_CONTRACT);expect(talk.system).toContain('Maximum 80 words');expect(guide.system).toContain('CODE / SOLUTION');expect(JSON.parse(talk.evidence).contextKey).toBe(JSON.parse(guide.evidence).contextKey)})
 it('invalidates old reasoning when question, evidence, code, or requirements move',()=>{const p=packet(),v=compileInterviewContext(p,'guide').versions;expect(versionsCurrent(v,p)).toBe(true);expect(versionsCurrent(v,{...p,evidenceVersion:8})).toBe(false);expect(versionsCurrent(v,{...p,codeVersion:5})).toBe(false);expect(versionsCurrent(v,{...p,question:{...p.question,id:'q2'}})).toBe(false);expect(versionsCurrent(v,{...p,task:{...p.task,version:4}})).toBe(false)})
})
