import { describe,expect,it,vi,afterEach } from 'vitest'
import { judgeLiveContext,routeDecision } from './typesafe'
import type { ContextPacket } from './types'
const context:ContextPacket={question:{id:'q',original:'Why is this failing?',text:'Why is this failing?',at:1},task:{objective:'Debug',requirements:[],constraints:[],phase:'debug',implementation:'allowed',version:1},visibleView:null,knownPaths:[],files:[],relations:[],tests:[],patches:[],patchReviews:[],conversation:[],evidenceVersion:1,codeVersion:1,schema:1,sessionId:'s',permission:'practice',contextKey:'k',budget:{maxCharacters:4000,usedCharacters:0,omittedPaths:[]}}
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs()})
describe('TypeSafe decision fabric',()=>{
 it('falls back without a server key and keeps the live path available',async()=>{vi.stubEnv('TYPESAFE_API_KEY','');const d=await judgeLiveContext(context,'talk',new AbortController().signal);expect(d.source).toBe('fallback');expect(routeDecision(d,'talk').suppress).toBe(false)})
 it('uses one fan-out response to suppress irrelevant low-value events',async()=>{vi.stubEnv('TYPESAFE_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({model:'jev-test',answers:{task_type:{type:'choice',choice:'irrelevant',confidence:.98},needs_response:{type:'noul',noul:.1},needs_deep_reasoning:{type:'noul',noul:.1},evidence_sufficient:{type:'noul',noul:.8},answer_stale:{type:'noul',noul:.1},complexity:{type:'score',score:0,confidence:1},intervention_value:{type:'score',score:0,confidence:1}}})}));const d=await judgeLiveContext(context,'talk',new AbortController().signal);expect(d.source).toBe('typesafe');expect(routeDecision(d,'talk').suppress).toBe(true)})
 it('escalates low-confidence or difficult work instead of trusting a brittle classification',async()=>{vi.stubEnv('TYPESAFE_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({model:'jev-test',answers:{task_type:{type:'choice',choice:'explain',confidence:.3},needs_response:{type:'noul',noul:1},needs_deep_reasoning:{type:'noul',noul:.2},evidence_sufficient:{type:'noul',noul:.5},answer_stale:{type:'noul',noul:.1},complexity:{type:'score',score:1,confidence:.5},intervention_value:{type:'score',score:2,confidence:1}}})}));expect(routeDecision(await judgeLiveContext(context,'talk',new AbortController().signal),'talk')).toMatchObject({deep:true,suppress:false,lane:'guide'})})
})
