import type { ContextPacket, Lane } from './types'
export type LiveTask='explain'|'navigate'|'implement'|'debug'|'test'|'review'|'system_design'|'behavioral'|'irrelevant'
export type Decision={source:'typesafe'|'fallback';model:string;task:LiveTask;taskConfidence:number;needsResponse:number;needsDeepReasoning:number;evidenceSufficient:number;answerStale:number;complexity:number;interventionValue:number;elapsedMs:number}
type A={type:string;choice?:string;confidence?:number;score?:number;noul?:number}
const TASKS:Record<LiveTask,string>={explain:'Direct technical explanation.',navigate:'Request a missing visible screen region.',implement:'Propose a code change.',debug:'Diagnose a failure or incorrect behavior.',test:'Plan or interpret verification.',review:'Review an observed edit.',system_design:'Architecture or distributed-system reasoning.',behavioral:'Behavioral or conversational response.',irrelevant:'No useful response is warranted.'}
const n=(a:A|undefined)=>a?.type==='noul'&&typeof a.noul==='number'?a.noul:.5
const s=(a:A|undefined)=>a?.type==='score'&&typeof a.score==='number'?a.score:0
export async function judgeLiveContext(context:ContextPacket,lane:Lane,signal:AbortSignal):Promise<Decision>{const t=performance.now(),key=process.env.TYPESAFE_API_KEY;if(!key)return fallback(context,lane,Math.round(performance.now()-t));try{const state=JSON.stringify({lane,question:context.question.text,task:context.task,visibleView:context.visibleView,knownPaths:context.knownPaths.slice(0,20),files:context.files.map(f=>({path:f.path,complete:f.complete,fragments:f.fragments.map(x=>({startLine:x.startLine,lines:x.lines.slice(0,80)}))})),tests:context.tests,patchReviews:context.patchReviews,conversation:context.conversation.slice(-6),evidenceVersion:context.evidenceVersion,codeVersion:context.codeVersion});const r=await fetch('https://api.typesafe.ai/v1/systemone',{method:'POST',signal:AbortSignal.any([signal,AbortSignal.timeout(1800)]),headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({state,model:process.env.TYPESAFE_MODEL||'jev-latest',questions:{task_type:{type:'choice',instructions:'Classify the current assistance task.',criteria:TASKS},needs_response:{type:'noul',instructions:'A useful assistant response is warranted now rather than waiting.'},needs_deep_reasoning:{type:'noul',instructions:'A strong answer requires substantial coding, debugging, review, or architecture reasoning.'},evidence_sufficient:{type:'noul',instructions:'Observed screen evidence is sufficient for the next grounded answer without inventing unseen code.'},answer_stale:{type:'noul',instructions:'An answer based on earlier evidence should be stale because question, code, tests, or requirements changed materially.'},complexity:{type:'score',instructions:'Rate reasoning complexity.',criteria:['Trivial direct response','Normal focused reasoning','Difficult multi-step reasoning','Frontier-level difficult reasoning']},intervention_value:{type:'score',instructions:'Rate value of proactively assisting now.',criteria:['Stay silent','Potentially helpful','Important','Urgent']}}})});if(!r.ok)return fallback(context,lane,Math.round(performance.now()-t));const d=await r.json() as {model:string;answers:Record<string,A>},a=d.answers.task_type;if(a?.type!=='choice'||!a.choice||!(a.choice in TASKS))return fallback(context,lane,Math.round(performance.now()-t));return{source:'typesafe',model:d.model,task:a.choice as LiveTask,taskConfidence:a.confidence??0,needsResponse:n(d.answers.needs_response),needsDeepReasoning:n(d.answers.needs_deep_reasoning),evidenceSufficient:n(d.answers.evidence_sufficient),answerStale:n(d.answers.answer_stale),complexity:s(d.answers.complexity),interventionValue:s(d.answers.intervention_value),elapsedMs:Math.round(performance.now()-t)}}catch{return fallback(context,lane,Math.round(performance.now()-t))}}
function fallback(c:ContextPacket,l:Lane,elapsedMs:number):Decision{const q=c.question.text.toLowerCase(),debug=/error|fail|bug|wrong|exception|race|stale|timeout/.test(q),review=l==='review';return{source:'fallback',model:'deterministic',task:review?'review':debug?'debug':l==='talk'?'explain':'implement',taskConfidence:0,needsResponse:1,needsDeepReasoning:l==='talk'&&!debug?0:1,evidenceSufficient:c.files.length||l==='talk'?1:0,answerStale:0,complexity:debug?2:l==='talk'?1:2,interventionValue:l==='talk'?2:1,elapsedMs}}
export function routeDecision(d:Decision,requested:Lane){const uncertain=d.source==='typesafe'&&d.taskConfidence<.55,suppress=!uncertain&&(d.task==='irrelevant'||d.needsResponse<.35||d.interventionValue<.5);if(suppress)return{lane:requested,deep:false,suppress:true};const deep=uncertain||d.needsDeepReasoning>=.6||d.complexity>=1.5||['implement','debug','review','system_design'].includes(d.task);return{lane:d.task==='review'?'review':requested==='talk'&&!deep?'talk':requested==='review'?'review':'guide' as Lane,deep,suppress:false}}
