import Anthropic from '@anthropic-ai/sdk'
import OpenAI from 'openai'
import { assertRepoModelConfigured, repoProvider } from './modelPolicy'

export type ModelUsage = { inputTokens: number; outputTokens: number }
type Effort = 'low' | 'medium' | 'high' | 'xhigh' | 'max'
type ModelRequest = { model: string; system: string; evidence: string; signal: AbortSignal; maxTokens?: number; onUsage?: (usage: ModelUsage) => void }
type ModelResult = { text: string; model: string; usage?: ModelUsage }

export class RepoModelResponseError extends Error {
  constructor(message: string, public model: string, public usage?: ModelUsage) { super(message) }
}

// Shared by live requests and benchmarks, so a benchmark does not quietly give
// one candidate a larger budget or a different reasoning setting than production.
export function repoGenerationSettings(model: string, synthesis = false): { maxTokens: number; effort?: Effort } {
  const reasoning = /^(?:gpt-[56]|claude-(?:fable|opus-5))/.test(model) || model.includes('gpt-oss')
  const supportsEffort = reasoning || model.startsWith('claude-sonnet-5')
  const configured = process.env.COPILOT_REPO_MAX_OUTPUT_TOKENS
  const maxTokens = configured ? Number(configured) : reasoning ? (synthesis ? 12_288 : 8_192) : (synthesis ? 4_500 : 2_200)
  if (!Number.isInteger(maxTokens) || maxTokens < 256 || maxTokens > 32_000) throw new Error('Invalid repository output token budget')
  if (!supportsEffort) return { maxTokens }
  const effort = process.env.COPILOT_REPO_REASONING_EFFORT || (reasoning ? 'low' : undefined)
  if (!effort) return { maxTokens }
  const allowed = model.includes('gpt-oss') ? ['low', 'medium', 'high'] : ['low', 'medium', 'high', 'xhigh', 'max']
  if (!allowed.includes(effort)) throw new Error('Unsupported repository reasoning effort')
  return { maxTokens, effort: effort as Effort }
}

function readUsage(input: number | undefined, output: number | undefined): ModelUsage | undefined {
  return Number.isInteger(input) && Number.isInteger(output) && input! >= 0 && output! >= 0
    ? { inputTokens: input!, outputTokens: output! } : undefined
}

function requireCompletion(reason: string | null | undefined, provider: 'claude' | 'openai', model: string, usage?: ModelUsage): void {
  if (reason === 'max_tokens' || reason === 'length') throw new RepoModelResponseError('Answer reached its output limit; narrow the question', model, usage)
  if (provider === 'claude' ? reason !== 'end_turn' && reason !== 'stop_sequence' : reason !== 'stop') {
    throw new RepoModelResponseError('Model did not complete its analysis; retry this question', model, usage)
  }
}

// Independent calls are deliberate: a failed reviewer cannot be disguised as a
// second opinion generated by the same fallback response. No silent fallbacks.
export async function callRepoModel(p: ModelRequest): Promise<ModelResult> {
  assertRepoModelConfigured(p.model)
  const settings = repoGenerationSettings(p.model)
  const signal = AbortSignal.any([p.signal, AbortSignal.timeout(28_000)])
  signal.throwIfAborted()
  if (repoProvider(p.model) === 'anthropic') {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY, maxRetries: 0, timeout: 28_000 })
    const result = await client.messages.create({ model: p.model, max_tokens: p.maxTokens ?? settings.maxTokens, ...(settings.effort ? { output_config: { effort: settings.effort } } : {}), system: p.system, messages: [{ role: 'user', content: p.evidence }] }, { signal })
    const usage = readUsage(result.usage?.input_tokens, result.usage?.output_tokens)
    requireCompletion(result.stop_reason, 'claude', result.model, usage)
    const text = result.content.flatMap((part) => part.type === 'text' ? [part.text] : []).join('\n')
    if (!text.trim()) throw new RepoModelResponseError('Model returned no analysis', result.model, usage)
    return { text, model: result.model, usage }
  }
  const groq = repoProvider(p.model) === 'groq'
  const client = new OpenAI({ apiKey: groq ? process.env.GROQ_API_KEY : process.env.OPENAI_API_KEY, baseURL: groq ? 'https://api.groq.com/openai/v1' : undefined, maxRetries: 0, timeout: 28_000 })
  const result = await client.chat.completions.create({ model: p.model, max_completion_tokens: p.maxTokens ?? settings.maxTokens, ...(settings.effort ? { reasoning_effort: settings.effort } : {}), messages: [{ role: 'system', content: p.system }, { role: 'user', content: p.evidence }] }, { signal })
  const usage = readUsage(result.usage?.prompt_tokens, result.usage?.completion_tokens)
  requireCompletion(result.choices[0]?.finish_reason, 'openai', result.model, usage)
  const text = result.choices[0]?.message.content
  if (!text?.trim()) throw new RepoModelResponseError('Model returned no analysis', result.model, usage)
  return { text, model: result.model, usage }
}

export async function* streamRepoModel(p: ModelRequest): AsyncGenerator<{ text: string; model: string }> {
  assertRepoModelConfigured(p.model)
  const settings = repoGenerationSettings(p.model, true)
  const signal = AbortSignal.any([p.signal, AbortSignal.timeout(50_000)])
  signal.throwIfAborted()
  if (repoProvider(p.model) === 'anthropic') {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY, maxRetries: 0, timeout: 50_000 })
    const stream = client.messages.stream({ model: p.model, max_tokens: p.maxTokens ?? settings.maxTokens, ...(settings.effort ? { output_config: { effort: settings.effort } } : {}), system: p.system, messages: [{ role: 'user', content: p.evidence }] }, { signal })
    let model = p.model
    let completed = false
    let stopped = false
    let inputTokens: number | undefined, outputTokens: number | undefined
    for await (const event of stream) {
      if (event.type === 'message_start') {
        model = event.message.model
        inputTokens = event.message.usage?.input_tokens
      }
      if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') yield { text: event.delta.text, model }
      if (event.type === 'message_delta') outputTokens = event.usage?.output_tokens
      if (event.type === 'message_delta' && event.delta.stop_reason) {
        requireCompletion(event.delta.stop_reason, 'claude', model, readUsage(inputTokens, outputTokens))
        completed = true
      }
      if (event.type === 'message_stop') stopped = true
    }
    if (!completed || !stopped) throw new RepoModelResponseError('Model stream ended without a completion event; the answer is incomplete', model, readUsage(inputTokens, outputTokens))
    const usage = readUsage(inputTokens, outputTokens)
    if (usage) p.onUsage?.(usage)
    return
  }
  const groq = repoProvider(p.model) === 'groq'
  const client = new OpenAI({ apiKey: groq ? process.env.GROQ_API_KEY : process.env.OPENAI_API_KEY, baseURL: groq ? 'https://api.groq.com/openai/v1' : undefined, maxRetries: 0, timeout: 50_000 })
  const stream = await client.chat.completions.create({ model: p.model, stream: true, stream_options: { include_usage: true }, max_completion_tokens: p.maxTokens ?? settings.maxTokens, ...(settings.effort ? { reasoning_effort: settings.effort } : {}), messages: [{ role: 'system', content: p.system }, { role: 'user', content: p.evidence }] }, { signal })
  let completed = false
  let usage: ModelUsage | undefined
  let model = p.model
  let completionError: RepoModelResponseError | undefined
  for await (const event of stream) {
    model = event.model || model
    const groqUsage = (event as unknown as { x_groq?: { usage?: { prompt_tokens?: number; completion_tokens?: number } } }).x_groq?.usage
    const reported = event.usage ?? (groq ? groqUsage : undefined)
    if (reported) usage = readUsage(reported.prompt_tokens, reported.completion_tokens)
    const text = event.choices[0]?.delta.content
    if (text) yield { text, model: event.model }
    const reason = event.choices[0]?.finish_reason
    if (reason) {
      // Read the trailing usage frame even when the completion was truncated.
      try { requireCompletion(reason, 'openai', model, usage); completed = true }
      catch (error) { completionError = error as RepoModelResponseError }
    }
  }
  if (completionError) throw new RepoModelResponseError(completionError.message, model, usage)
  if (!completed) throw new RepoModelResponseError('Model stream ended without a completion event; the answer is incomplete', model, usage)
  if (usage) p.onUsage?.(usage)
}
