import Anthropic from '@anthropic-ai/sdk'
import OpenAI from 'openai'
import { assertRepoModelConfigured, repoProvider } from './modelPolicy'

type ModelRequest = { model: string; system: string; evidence: string; signal: AbortSignal; maxTokens?: number }
type ModelResult = { text: string; model: string }

function requireCompletion(reason: string | null | undefined, provider: 'claude' | 'openai'): void {
  if (reason === 'max_tokens' || reason === 'length') throw new Error('Answer reached its output limit; narrow the question')
  if (provider === 'claude' ? reason !== 'end_turn' && reason !== 'stop_sequence' : reason !== 'stop') {
    throw new Error('Model did not complete its analysis; retry this question')
  }
}

// Independent calls are deliberate: a failed reviewer cannot be disguised as a
// second opinion generated by the same fallback response. No silent fallbacks.
export async function callRepoModel(p: ModelRequest): Promise<ModelResult> {
  assertRepoModelConfigured(p.model)
  const signal = AbortSignal.any([p.signal, AbortSignal.timeout(28_000)])
  signal.throwIfAborted()
  if (repoProvider(p.model) === 'anthropic') {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY, maxRetries: 0, timeout: 28_000 })
    const result = await client.messages.create({ model: p.model, max_tokens: p.maxTokens ?? 2200, system: p.system, messages: [{ role: 'user', content: p.evidence }] }, { signal })
    requireCompletion(result.stop_reason, 'claude')
    const text = result.content.flatMap((part) => part.type === 'text' ? [part.text] : []).join('\n')
    if (!text.trim()) throw new Error('Model returned no analysis')
    return { text, model: result.model }
  }
  const groq = repoProvider(p.model) === 'groq'
  const client = new OpenAI({ apiKey: groq ? process.env.GROQ_API_KEY : process.env.OPENAI_API_KEY, baseURL: groq ? 'https://api.groq.com/openai/v1' : undefined, maxRetries: 0, timeout: 28_000 })
  const result = await client.chat.completions.create({ model: p.model, max_completion_tokens: p.maxTokens ?? 2200, messages: [{ role: 'system', content: p.system }, { role: 'user', content: p.evidence }] }, { signal })
  requireCompletion(result.choices[0]?.finish_reason, 'openai')
  const text = result.choices[0]?.message.content
  if (!text?.trim()) throw new Error('Model returned no analysis')
  return { text, model: result.model }
}

export async function* streamRepoModel(p: ModelRequest): AsyncGenerator<{ text: string; model: string }> {
  assertRepoModelConfigured(p.model)
  const signal = AbortSignal.any([p.signal, AbortSignal.timeout(50_000)])
  signal.throwIfAborted()
  if (repoProvider(p.model) === 'anthropic') {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY, maxRetries: 0, timeout: 50_000 })
    const stream = client.messages.stream({ model: p.model, max_tokens: p.maxTokens ?? 4500, system: p.system, messages: [{ role: 'user', content: p.evidence }] }, { signal })
    let model = p.model
    let completed = false
    let stopped = false
    for await (const event of stream) {
      if (event.type === 'message_start') model = event.message.model
      if (event.type === 'content_block_delta' && event.delta.type === 'text_delta') yield { text: event.delta.text, model }
      if (event.type === 'message_delta' && event.delta.stop_reason) {
        requireCompletion(event.delta.stop_reason, 'claude')
        completed = true
      }
      if (event.type === 'message_stop') stopped = true
    }
    if (!completed || !stopped) throw new Error('Model stream ended without a completion event; the answer is incomplete')
    return
  }
  const groq = repoProvider(p.model) === 'groq'
  const client = new OpenAI({ apiKey: groq ? process.env.GROQ_API_KEY : process.env.OPENAI_API_KEY, baseURL: groq ? 'https://api.groq.com/openai/v1' : undefined, maxRetries: 0, timeout: 50_000 })
  const stream = await client.chat.completions.create({ model: p.model, stream: true, max_completion_tokens: p.maxTokens ?? 4500, messages: [{ role: 'system', content: p.system }, { role: 'user', content: p.evidence }] }, { signal })
  let completed = false
  for await (const event of stream) {
    const text = event.choices[0]?.delta.content
    if (text) yield { text, model: event.model }
    const reason = event.choices[0]?.finish_reason
    if (reason) {
      requireCompletion(reason, 'openai')
      completed = true
    }
  }
  if (!completed) throw new Error('Model stream ended without a completion event; the answer is incomplete')
}
